import getUsers from "../../../../services/getUsers";

const UserDetails = async (props) => {
    const users = await getUsers();
    const currentUser = users[props.params.id - 1]
    console.log("current user->", currentUser)
    return (
        <div>
            <h4>User Details</h4>
            <h3>Name: {currentUser.name}</h3>
            <h3>Username: {currentUser.username}</h3>
            <h3>Email: {currentUser.email}</h3>
            <h3>Website: {currentUser.website}</h3>
            <h3>Phone: {currentUser.phone}</h3>
        </div>
    )
}

export default UserDetails

export async function generateStaticParams () {
    const users = await getUsers();
    return users.map((user) => ({
        id: user.id.toString()
    }))
    // above we have to write the same name as given to the dynamic route
    // here if we check under the .next/server/app/users then we will find the static 10 user pages 
    // generated by next.js as we have used static rendering
}